export const majorList = [
    { major: 'Accounting and Finance' },
    { major: 'Agriculture' },
    { major: 'Biotechnology & Biomedical' },
    { major: 'Business' },
    { major: 'Computer Science and IT' },
    { major: 'Design' },
    { major: 'Economics' },
    { major: 'Education' },
    { major: 'Engineering' },
    { major: 'Hospitality and Tourism Management' },
    { major: 'Law' },
    { major: 'Mass Communication' },
    { major: 'Medicine and Health' },
    { major: 'Psychology' },
];
